NAME_OR_ID = "Name or ID to look up"
POKEMON_NAME_OR_ID = "Pokemon name or Pokedex number"
FORM_NAME_OR_ID = "Pokemon form name or ID"
MOVE_NAME_OR_ID = "Move name or ID"
ITEM_NAME_OR_ID = "Item name or ID"
ABILITY_NAME_OR_ID = "Ability name or ID"
TYPE_NAME_OR_ID = "Type name or ID, for example fire or 10"
REGION_NAME_OR_ID = "Region name or ID"
LOCATION_NAME_OR_ID = "Location name or ID"
LOCATION_AREA_NAME_OR_ID = "Location area name or ID"
GENERATION_NAME_OR_ID = "Generation name or ID"
POKEDEX_NAME_OR_ID = "Pokedex name or ID"
VERSION_NAME_OR_ID = "Version name or ID"
VERSION_GROUP_NAME_OR_ID = "Version group name or ID"
NATURE_NAME_OR_ID = "Nature name or ID"
BERRY_NAME_OR_ID = "Berry name or ID"
EGG_GROUP_NAME_OR_ID = "Egg group name or ID"
GROWTH_RATE_NAME_OR_ID = "Growth rate name or ID"
EVOLUTION_TRIGGER_NAME_OR_ID = "Evolution trigger name or ID"
DAMAGE_CLASS_NAME_OR_ID = "Damage class name or ID"
LEARN_METHOD_NAME_OR_ID = "Learn method name or ID"
MACHINE_ID = "Machine ID"
EVOLUTION_CHAIN_ID = "Evolution chain ID"

NO_CACHE = "Fetch fresh data instead of using the local cache"
FORMAT = "Choose table output or JSON output"
LIMIT = "Number of results to show"
OFFSET = "Number of results to skip"
MOVE_FILTER = "Only show or check this move"
METHOD_FILTER = "Only include this learn method: level-up, machine, tutor, or egg"
MOVE_NAME = "Move name to check"
OUTPUT_PATH = "Where to save the downloaded image"
RESOURCE = "Resource type, currently only pokemon"
RESOURCE_NAME_OR_ID = "Name or ID to download"
SPRITE_VARIANT = (
    "Sprite variant: front_default, front_shiny, back_default, back_shiny, "
    "front_female, front_shiny_female"
)
